language: python
# Existing Python versions
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
# Enable 3.10 without globally enabling sudo and dist: jammy for other build jobs
matrix:
  include:
    - python: 3.10
      dist: jammy
      sudo: true
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install -r requirements.txt
  - python setup.py -q install
script:
  - pytest
after_success:
  - pytest --cov=./meterbus
  - codecov
branches:
  only:
    - master
